# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-x509-exporter

- name: Create x509-exporter group
  ansible.builtin.group:
    name: "{{ x509_exporter_group }}"
    system: true
    state: present

- name: Create x509-exporter user
  ansible.builtin.user:
    name: "{{ x509_exporter_user }}"
    group: "{{ x509_exporter_group }}"
    system: true
    shell: /sbin/nologin
    create_home: false
    state: present

- name: Download x509-exporter archive
  ansible.builtin.get_url:
    url: "{{ x509_exporter_download_url }}"
    dest: "/tmp/{{ x509_exporter_binary_name }}.tar.gz"
    checksum: "{{ x509_exporter_checksum }}"
    mode: "0644"

- name: Extract x509-exporter binary
  ansible.builtin.unarchive:
    src: "/tmp/{{ x509_exporter_binary_name }}.tar.gz"
    dest: "{{ x509_exporter_install_dir }}"
    include: "{{ x509_exporter_binary_name }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"
  notify: Restart x509-exporter

- name: Create systemd service
  ansible.builtin.template:
    src: x509-exporter.service.j2
    dest: /etc/systemd/system/x509-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart x509-exporter

- name: Enable and start x509-exporter service
  ansible.builtin.systemd:
    name: x509-exporter
    enabled: true
    state: started
    daemon_reload: true
