# SPDX-License-Identifier: MIT-0
---
# handlers file for ansible-role-x509-exporter

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart x509-exporter
  ansible.builtin.systemd:
    name: x509-exporter
    state: restarted
